name = "dx"
version = "0.0.1"
title = "Enhanced Developing Experience"
description = "Orchestrate don't just own your code"
author = "essensefromexistence"
workspace = ["frontend/www", "frontend/mobile"]
editors = [
    "vscode",
    "vim",
    "gitpod",
    "github-codespace",
    "replit",
    "firebase-studio",
    "cursor",
    "windsurf",
    "stackblitz",
]

[forge]
repository = "https://dx.vercel.app/essensefromexistence/dx"
container = "none"
pipeline = "none"
tasks = "none"
items = ["cli", "docs", "examples", "packages", "scripts", "style", "tests"]

[stack]
columns = ["language", "runtime", "compiler", "bundler", "package_manager","test_runner", "framework", "dependencies"]

[stack.javascript]
language = "javascript/typescript"
runtime = "bun"
compiler = "tsc"
bundler = "vite"
package_manager = "bun"
test_runner = "bun test runner"
framework = "react"
dependencies = ["react", "vite", "typescript", "tailwindcss", "shadcn-ui", "zustand", "@tanstack/react-query", "zod", "react-hook-form"]

[stack.python]
language = "python"
runtime = "cpython"
compiler = "-"
bundler = "-"
package_manager = "uv"
test_runner = "pytest"
framework = "django"
dependencies = ["django", "djangorestframework", "uvicorn", "fastapi"]

[stack.rust]
language = "rust"
runtime = "native"
compiler = "rustc"
bundler = "-"
package_manager = "cargo"
test_runner = "cargo test"
framework = "actix-web"
dependencies = ["tokio", "serde", "axum", "diesel"]

[style]
path = "@/style"
themes = ["dx", "vercel", "claude"]

[ui]
path = "@/components/ui"
components = ["button", "card", "modal", "navbar", "footer"]

[media]
columns = ["path", "images", "videos", "sounds", "assets"]

[media.images]
path = "@/public/images/*"
images = ["dummy1.jpg", "dummy2.png"]

[media.videos]
path = "@/public/videos/*"
videos = ["dummy1.mp4"]

[media.sounds]
path = "@/public/sounds/*"
sounds = ["dummy1.wav"]

[media.assets]
path = "@/public/assets/*"
assets = ["dummy1.asset"]

[i18n]
columns = ["path", "default", "dev", "prod"]

[i18n.locales]
path = "@/locales"
default = "en-US"
dev = ["en-US"]
prod = ["all"]

[i18n.ttes]
path = "./ttses"
default = "en-US"
dev = ["en-US", "bn-BD"]
prod = ["all"]

[icon]
path = "@/components/icons"
pack = "lucide-react"
variant = "default"

[font]
path = "@/font"
default = "Inter"
primary = "Manrope"
secondary = "RobotoMono"
