name                = dx
version             = 0.0.1
title               = "Enhanced Developing Experience"
description         = "Orchestrate don't just own your code"
author              = essensefromexistence
workspace           = frontend/www | frontend/mobile
editors             = vscode | vim | neovim | github-codespace | replit | firebase-studio | cursor | windsurf

[forge]
repository          = https://dx.vercel.app/essensefromexistence/dx
container           = none
pipeline            = none
tasks               = none
items               = cli | docs | examples | packages | scripts | style | tests

[stack]
js                  = javascript/typescript | bun       | tsc       | vite    | bun   | react
python              = py                    | python    | cpython   | -       | uv    | django
rust                = rs                    | rust      | native    | rustc   | cargo | actix-web

[style]
path                = @/style
themes              = dx

[ui]
path                = @/components/ui
components          = button | card | modal | navbar | footer | all

[media]
images              = @/media/images
videos              = @/media/videos
sounds              = @/media/sounds
assets              = @/media/assets

[i18n.locales]
path                = @/locales
default             = en-US
dev                 = en-US
prod                = all
[i18n.ttses]
path                = @/media/sounds
default             = en-US
dev                 = en-US | bn-BD
prod                = all

[icon]
path                = @/icons
pack                = lucide-react
variant             = default

[font]
path                = @/fonts
default             = Inter
primary             = Manrope
secondary           = RobotoMono
