[package]
name = "mago-guard"
description = "A PHP dependencies guard that helps keep your architecture clean."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mago-atom = { workspace = true }
mago-reporting = { workspace = true }
mago-span = { workspace = true }
mago-syntax = { workspace = true }
mago-names = { workspace = true }
mago-collector = { workspace = true }
mago-syntax-core = { workspace = true }
mago-database = { workspace = true }
mago-codex = { workspace = true }
ahash = { workspace = true }
serde = { workspace = true }
bumpalo = { workspace = true }

[dev-dependencies]
mago-syntax = { workspace = true }
mago-prelude = { workspace = true, features = ["build"] }
indoc = { workspace = true }
toml = { workspace = true }
