[package]
name = "dx-compat-html"
version = "0.1.0"
edition = "2024"
description = "HTML Rewriter for DX"
license = "MIT OR Apache-2.0"

[dependencies]
lol_html = "2.0"
thiserror.workspace = true

[dev-dependencies]
proptest = "1.4"
