[package]
name = "dx-www-print"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Print stylesheet generator"

[lib]
path = "src/lib.rs"

[dependencies]
lightningcss = "1.0.0-alpha.68"
