[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "cpp-linter"
description = "Run clang-format and clang-tidy on a batch of files."
readme = "bindings/python/README.md"
keywords = ["clang", "clang-tools", "linter", "clang-tidy", "clang-format"]
license = {text = "MIT License"}
requires-python = ">=3.9"
authors = [
    { name = "Brendan Doherty", email = "2bndy5@gmail.com" },
    { name = "Xianpeng Shen", email = "xianpeng.shen@gmail.com" },
]
classifiers = [
    # https://pypi.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.scripts]
cpp-linter = "cpp_linter:main"

[project.urls]
source =  "https://github.com/cpp-linter/cpp-linter-rs"
tracker = "https://github.com/cpp-linter/cpp-linter-rs/issues"

[tool.maturin]
features = ["pyo3/extension-module"]
include = [
    {path = "cpp_linter.pyi", format = "sdist"},
]
exclude = [
    {path = "**/tests/**", format="sdist"},
    {path = "**/examples/**", format="sdist"},
    {path = "**/docs/**", format="sdist"},
]
manifest-path = "bindings/python/Cargo.toml"

[dependency-groups]
dev = [
    "maturin==1.9.1",
    "mypy==1.17.0",
    "patchelf==0.17.2.2 ; sys_platform == 'linux'",
    "pre-commit>=4.2.0",
    "ruff==0.12.4",
]
test = [
    "meson==1.8.2",
]

[tool.uv]
# we don't need to build the python binding every time we spin up a venv
package = false

[tool.uv.workspace]
members = ["docs"]
