[package]
name = "dx-www-fallback"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "HTML fallback mode"

[lib]
path = "src/lib.rs"

[dependencies]
maud = "0.26"
