[package]
name = "dx-test-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
serde = { workspace = true }
